- name: Setup EC2 hosts
  hosts: nodes
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Create student user, add to 'wheel' group
      user:
        name: student
        groups: wheel
        append: yes
        state: present
        create_home: yes
        password: "{{ lookup('env', 'SSH_PASSWORD') | password_hash('sha512') }}"
        shell: /bin/bash
    - name: Enable SSH password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^(#)?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
